### ISSUE TITLE
inactive parallel instances cannot get activated for step function in window iteration

### ISSUE THREAD

**Issue by ChristianLehner98** [senorcarbone/time-killer#3]
It appears that parallel instances that are not active in the entry function of an iteration over a window because no stream element of that window is assigned to them are also ignored in the step function of any later superstep for the same window, even if there are now elements with a key that is assigned to such an instance.

Although the problem in practice often doesn't occur with large enough windows because all parallel instances are active to begin with, in edge cases this means that it can technically not be guaranteed that the iteration still works if the key of an emitted message is not already the key of an element of the input stream in the current window (that will be processed in the entry function).

Is this a known and intended restriction or a bug?

Once again my diagnosis of the problem is limited to some tests I made myself and it is possible that there are other factors to when this does(n't) work that I haven't yet discovered.

**Comment by ChristianLehner98** [comment]
I have an example here, too:

https://github.com/ChristianLehner98/time-killer/blob/master/flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/iteration/issuedemonstrations/lostmessagestest/LostMessagesExample.java

output:
[lost messages.txt](https://github.com/senorcarbone/time-killer/files/3281539/lost.messages.txt)

I think one can see that some messages are not received as I described in the original comment.

**Comment by ChristianLehner98** [comment]
Oh yeah, completely forgot to post it here: This is just obvioously caused by the if-condition in lines 108-110 in flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/windowing/WindowMultiPassOperator.java and can be fixed b getting rid of it. I don't know what negative consequences taht may have. I think it's not worth making a pull request for that.

**Comment by senorcarbone** [comment]
Please try out the new stateful loop API and close this issue if resolved

**Comment by senorcarbone** [comment]
On a side note this issue depends strongly on the way watermarks are generated in your sources. When parallel sources are running you need to ensure that even if they do not emit data they have to emit watermarks consistently (you can align with epoch time) in order to allow for parallel activation of stream window loops

**Comment by ChristianLehner98** [comment]
Was this supposed to go to https://github.com/senorcarbone/time-killer/issues/2#issue-443090494 ? If yes I think I understand and acknowledge that the issue was written on an incomplete undertanding I had, that is now clearer, but I will comment on that at a later time.

I don't think it is the cause for this issue here though. As I wrote in the previous comment, that one seems rather clear. A context is only added to the activeIterations field in a [WindowMultiPassOperator](https://github.com/senorcarbone/time-killer/blob/master/flink-streaming-java/src/main/java/org/apache/flink/streaming/runtime/operators/windowing/WindowMultiPassOperator.java) instance when processElement1 is called, which only happens when there is an entry record. If that is not the case the check in processElement2 fails and the feedback record is not actually processed.

I haven't tested if the new API fixes the problem, but I don't see how it would considering the situation explained above that doesn't seem to have been adressed.
