### ISSUE TITLE
problems with persistent state

### ISSUE THREAD

**Issue by ChristianLehner98** [senorcarbone/time-killer#4]
I have made a Fork of ths repository (https://github.com/ChristianLehner98/time-killer) in which I tried to show more clearly what problems I have with the use of persistent state in window iterations. 

The main thing I changed is the Streaming Page rank example, where I altered the source in such a way that their are certain sleep times between the creation of elements at the source. Other than that I mostly just changed some details and the messages written to the error output (and introduced actual logging that I haven't really used yet, so you can probably ignore that). I also changed the input IDs to make it easier to differtiate between windows.

I attached some traces I generated with different sleep times between the elements. If you look at the trace with sleep time 1s you can see that e.g. in line 31 the state of subtask 2 is already correctly updated [#Vertices:[1, 2, 3], #Ranks:[1=1.0, 2=1.0, 3=1.0]]. However, when significantly after that it is read again in the same subtask in line 4 it is empty again. You can see many similar examples in all traces. I tried to stay as close to the example code already present here, I can send you a simpler example as well when I have a bit of time.
[traces.zip](https://github.com/senorcarbone/time-killer/files/3262247/traces.zip)

**Comment by ChristianLehner98** [comment]
I have now finally found out what exactly the cause for this weird behaviour of the state is. As I already knew keyed state is used, but in the examples you seemed to have used it as if it was operator state. However, until recently I didn't understand what key is used. By allowng access to the current key in the stateTable of the HeapMapState (which is what I used for these tests in my setup), I could see that the key used for accesing state seems to be the key of the last element entered in the current window. This state partitioning to me makes no sense. 

An example for demonstration of what I mean:
code:
https://github.com/ChristianLehner98/time-killer/blob/master/flink-examples/flink-examples-streaming/src/main/java/org/apache/flink/streaming/examples/iteration/issuedemonstrations/SaveAndReadPersistentStateExample.java

output: 
[trace_persistent_state_problem.txt](https://github.com/senorcarbone/time-killer/files/3294128/trace_persistent_state_problem.txt)

As one can see, while the HeapMapState is always the same, the key is different depending on the window. For example in line 72 of the output the key is 3, in line 78 it is 1. This means that one  can not reliably read the entries of the MapState, since one only gets the mapping associated with the key of the current window. In essence, I believe this is highly unintuitive and probably not what you want.

I haven't figured out how and where this key is set and what one could do about it. Maybe you can understand that a bit better since you have been more involved with Flink for a longer time.

**Comment by senorcarbone** [comment]
very helpful info @ChristianLehner98 ! I have some free time this week so stay tuned, I am going to attempt a general state workaround that will do the trick
